"""Render the synthetic markdown factsheets into PDFs.

Produces real PDF fund factsheets from the markdown in
`data/synthetic/foundry_iq/factsheets/*.md` so they can be pushed through the
live ingest path (upload -> Content Safety -> blob -> Content Understanding).

The content is entirely synthetic (generated by `scripts.synthetic.generate`);
these PDFs are safe demo assets with no real client or market data.

Run:
    cd backend
    python -m scripts.synthetic.generate                 # produce markdown
    python -m scripts.synthetic.render_factsheets_pdf     # markdown -> PDF
    python -m scripts.synthetic.render_factsheets_pdf --md path/to/one.md
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Ensure the backend package root is importable when run directly.
_BACKEND_ROOT = Path(__file__).resolve().parents[2]
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from fpdf import FPDF

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

FACTSHEET_DIR = _BACKEND_ROOT / "data" / "synthetic" / "foundry_iq" / "factsheets"


def _clean(text: str) -> str:
    """Strip inline markdown emphasis and normalise to latin-1-safe text."""
    text = text.replace("**", "").replace("`", "")
    replacements = {
        "\u2019": "'",
        "\u2018": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2192": "->",
        "\u2265": ">=",
        "\u2264": "<=",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", "replace").decode("latin-1")


def _render_table(pdf: FPDF, rows: list[list[str]]) -> None:
    if not rows:
        return
    col_count = max(len(r) for r in rows)
    usable = pdf.w - pdf.l_margin - pdf.r_margin
    col_width = usable / col_count
    for i, row in enumerate(rows):
        pdf.set_font("Helvetica", "B" if i == 0 else "", 10)
        for cell in row:
            pdf.cell(col_width, 7, _clean(cell.strip()), border=1)
        pdf.ln(7)
    pdf.ln(2)


def render_markdown(md_path: Path, pdf_path: Path) -> None:
    """Render a single markdown factsheet to a PDF."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    table_buffer: list[list[str]] = []

    def flush_table() -> None:
        nonlocal table_buffer
        if table_buffer:
            # Drop the markdown separator row (---|---).
            cleaned = [
                r for r in table_buffer
                if not all(set(c.strip()) <= {"-", ":", " "} for c in r)
            ]
            _render_table(pdf, cleaned)
            table_buffer = []

    for raw in md_path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if line.startswith("|"):
            table_buffer.append([c for c in line.strip("|").split("|")])
            continue
        flush_table()

        pdf.set_x(pdf.l_margin)
        if not line.strip():
            pdf.ln(3)
        elif line.startswith("# "):
            pdf.set_font("Helvetica", "B", 16)
            pdf.multi_cell(0, 9, _clean(line[2:]))
            pdf.ln(1)
        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.ln(2)
            pdf.multi_cell(0, 8, _clean(line[3:]))
        elif line.startswith("- "):
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, _clean("  - " + line[2:]))
        elif line.startswith("> "):
            pdf.set_font("Helvetica", "I", 11)
            pdf.multi_cell(0, 6, _clean(line[2:]))
        else:
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 6, _clean(line))

    flush_table()
    pdf.output(str(pdf_path))
    logger.info("Rendered %s", pdf_path.name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--md", type=str, default=None, help="Render a single markdown file.")
    parser.add_argument(
        "--out-dir",
        type=str,
        default=str(FACTSHEET_DIR / "pdf"),
        help="Output directory for the generated PDFs.",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.md:
        sources = [Path(args.md)]
    else:
        sources = sorted(FACTSHEET_DIR.glob("*.md"))
    if not sources:
        raise FileNotFoundError(
            f"No markdown factsheets found in {FACTSHEET_DIR}. "
            "Run 'python -m scripts.synthetic.generate' first."
        )

    for md_path in sources:
        render_markdown(md_path, out_dir / f"{md_path.stem}.pdf")

    logger.info("Wrote %d PDF factsheet(s) to %s", len(sources), out_dir)


if __name__ == "__main__":
    main()
